### ISSUE TITLE
mobile menu doesn't open on click

### ISSUE THREAD

**Issue by markpfaff** [paulzwu/NSC-AD410-TIP-GROUP2#163]

**Comment by kswarthout** [comment]
This is happening because the responsive nav js script keeps getting deleted or overridden in the script tags. I've fixed it a few times now, but it keeps getting changed back. I went through this weekend page by page to fix the resource links, and try to address conflicts and what not, but....it got changed again.

**Comment by markpfaff** [comment]
Can you post this to slack with a screenshot. Maybe someone else keeps
trying to "fix" it

-- 
Mark Pfaff
(206)669-5074 <2066695074>

From: Kari Bullard <notifications@github.com> <notifications@github.com>
Reply: paulzwu/NSC-AD410-TIP-GROUP2
<reply@reply.github.com>
<reply@reply.github.com>
Date: June 5, 2017 at 7:31:56 PM
To: paulzwu/NSC-AD410-TIP-GROUP2 <nsc-ad410-tip-group2@noreply.github.com>
<nsc-ad410-tip-group2@noreply.github.com>
CC: Mark Pfaff <markdpfaff@gmail.com> <markdpfaff@gmail.com>, Assign
<assign@noreply.github.com> <assign@noreply.github.com>
Subject:  Re: [paulzwu/NSC-AD410-TIP-GROUP2] mobile menu doesn't open on
click (#163)

This is happening because the responsive nav js script keeps getting
